Edit Question2ViewController.swift and Question2Cell.swift
wataru0/intern_2week_study_ios pull request #2
Opened 2020-08-14 03:44 UTC by wataru0

課題
---
- 課題2
[URL](https://github.com/Caraquri/intern_2week_study_ios/issues/2)

概要
---
1. areaTextsの内容をcellのlabelに表示させてください.
1. Nukeというライブラリを用いて，cellのImageViewに画像を表示させてください．表示させる画像は自由なものを使用してよいです.
ただし，画像はURLで設定する必要があるため、URLを設定することに気をつけて下さい．
1. cellをタップした際にUIAlertControllerを用いてアラートを表示する処理を実装してください．その際は以下の条件を満たすように作成してください．

    * titleはcellに表示している文字列を使用して下さい．
    * messageは自由に設定してください．
    * アクションは”OK”を表示してください．

特に確認して頂きたい項目
---
- xibを利用したカスタムセルの実装部分

動作確認用 Screenshots
---
<img src="https://user-images.githubusercontent.com/44032125/90211465-b6335980-de2b-11ea-9b60-ab8386afdc49.gif" width="300" />

参考URL
---
- [チーバくん](https://j-town.net/tokyo/column/gotochicolumn/240477.html?p=all)
- [【Swift】TableViewでセルの高さを変更しよう](https://qiita.com/misakiagata/items/3793a00e386c7a3ff39a)
- [UITableView周りいろいろ その②cellをタップしたときの処理](http://mjk0513.hateblo.jp/entry/2015/09/19/230206)
- [[iPhone] UIAlertController アラート表示の設定](https://i-app-tec.com/ios/uialertcontroller.html)
- [Swift：UITableView(XIBを使ってUITableViewCellをカスタム)](https://asky.hatenablog.com/entry/2018/04/29/022044)

2020-08-15 04:19 UTC, ghost requested changes
課題1の内容と一緒にPRを送らないで欲しいです。レビューがやりにくいです。:pray:
課題1をマージ&反映したらまた依頼お願いします。
レビューが遅く申し訳ありませんが、課題の進め方等分からなかったらslackを活用して聞いて下さいね。

2020-08-15 04:19 UTC, msugai-cq commented on intern_2week_study/Question/Question2/Question2ViewController.swift
> +        self.tableView.register(UINib(nibName: "Question2Cell", bundle: nil), forCellReuseIdentifier: "question2Cell")
R.swiftを使うと下記のようにかけるはずです。
```
tableView.register(R.nib.question2Cell)
```
https://github.com/mac-cain13/R.swift/blob/master/Documentation/Examples.md#reusable-table-view-cells

2020-08-15 04:19 UTC, msugai-cq commented on intern_2week_study/Question/Question2/Question2ViewController.swift
> +        self.tableView.dataSource = self
```
tableView.dataSource = self
```
でよいです。
selfは本当に必要な際につけましょう、そうするとselfがついている処理を注意して見れるようになります。 👀

2020-08-15 04:19 UTC, msugai-cq commented on intern_2week_study/Question/Question2/Question2ViewController.swift
> +    override func didReceiveMemoryWarning() {
これ必要無いと思います。

2020-08-15 04:19 UTC, msugai-cq commented on intern_2week_study/Question/Question2/Question2ViewController.swift
> +        //cell.textLabel?.text = areaTexts[indexPath.row]
不要コメントは削除しましょう 👮

2020-08-15 04:19 UTC, msugai-cq commented on intern_2week_study/Question/Question2/Question2ViewController.swift
> +            print("ok")
これいらないかも

2020-08-15 04:19 UTC, msugai-cq commented on intern_2week_study/Question/Question2/Question2ViewController.swift
> +        present(alert, animated: true, completion: nil)
presentにはデフォルト引数が使われているため handlerにnilを指定しなくて良いです。
```
present(alert, animated: true)
```

```
open func present(_ viewControllerToPresent: UIViewController, animated flag: Bool, completion: (() -> Void)? = nil)
```

2020-08-15 04:19 UTC, msugai-cq commented on intern_2week_study/Question/Question2/Question2ViewController.swift
> +    // ヘッダーの大きさ
```
// ヘッダーの大きさ
    func tableView(_ tableView: UITableView, heightForHeaderInSection section: Int) -> CGFloat {
        return CGFloat.leastNormalMagnitude
    }

// フッターの大きさ
    func tableView(_ tableView: UITableView, heightForFooterInSection section: Int) -> CGFloat {
        return CGFloat.leastNormalMagnitude
    }
```
これ無くても動きそうです

2020-08-17 08:55 UTC, wataru0 commented
課題1をマージ，反映した後に修正しました．
レビューお願いします．

2020-08-17 11:26 UTC, ghost approved these changes
だいぶ良くなっています！
対応ありがとうございます！
何か分からないことがあったらしつもんして下さいね:+1:
LGTM

2020-08-17 11:26 UTC, msugai-cq commented on intern_2week_study/Question/Question2/Question2ViewController.swift
> +        guard let cell = self.tableView.dequeueReusableCell(withIdentifier: "question2Cell") as? Question2Cell else {
これも R.swiftを用いて楽にできます。:eyes:
```
guard let cell = tableView.dequeueReusableCell(withIdentifier: R.reuseIdentifier. question2Cell, for: indexPath)
```

2020-08-17 11:26 UTC, msugai-cq commented on intern_2week_study/Question/Question2/Question2ViewController.swift
> +        alert.addAction(UIAlertAction(title: "OK", style: .default, handler: { (_ action: UIAlertAction!) -> Void in
ココ `handler `は省略できるのでしてみましょう 💪 

UIAlertActionにはデフォルト引数が使われているため handlerにnilを指定しなくて良いです。
```
UIAlertAction(title: "OK", style: .default)
```

```
public convenience init(title: String?, style: UIAlertAction.Style, handler: ((UIAlertAction) -> Void)? = nil)
```

2020-08-17 11:26 UTC, msugai-cq commented on intern_2week_study/Question/Question2/Question2Cell.swift
> +    public func setCell(cellLabel: String, url: String) {
細かくなってしまうのですが、このメソッド名微妙かも
```
public func setCell(cellLabel: String, url: String) {
```
なぜ微妙かというとCellのクラス内なので、set`Cell`という単語はいらない。
`cellLabel`だとどんな情報が必要だか分かりにくい、からです。

そうなるとこんな感じのメソッド名はどうでしょうか
これは一例のため、他の人に見てもらい納得できるものならそれで良いです。
```
public func setArea(_ name: String, withImageURL url: URL) {
```
Swiftでは、英語で自然に読めるように心がけた命名が推奨されています。  
https://dev.classmethod.jp/articles/swift-api-design-guidelines-reading-strive-for-fluent-usage/  
全てを英文のように書くことは難しいので、頭の片隅に置いておいて欲しいです。

2020-08-18 01:58 UTC, merged